=== Gurraza/project-slots-backend/schemas/slot-config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Slot Engine Game Config",
    "type": "object",
    "required": [
        "Cols",
        "Rows",
        "Symbols"
    ],
    "additionalProperties": false,
    "properties": {
        "Cols": {
            "type": "integer",
            "minimum": 1
        },
        "Rows": {
            "type": "integer",
            "minimum": 1
        },
        "Symbols": {
            "type": "array",
            "minItems": 1,
            "items": {
                "$ref": "#/definitions/symbol"
            }
        },
        "Features": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/feature"
            }
        }
    },
    "definitions": {
        "symbol": {
            "type": "object",
            "required": [
                "ID",
                "Name",
                "Payouts",
                "WeightConfig"
            ],
            "additionalProperties": false,
            "properties": {
                "ID": {
                    "type": "integer",
                    "minimum": 0
                },
                "Name": {
                    "type": "string",
                    "minLength": 1
                },
                "Payouts": {
                    "type": "array",
                    "items": {
                        "type": "number",
                        "minimum": 0
                    }
                },
                "MatchesWith": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "default": [ ]
                },
                "WeightConfig": {
                    "$ref": "#/definitions/weightConfig"
                }
            }
        },
        "weightConfig": {
            "type": "object",
            "required": [
                "FixedWeight"
            ],
            "additionalProperties": false,
            "properties": {
                "FixedWeight": {
                    "type": "number",
                    "minimum": 0
                },
                "Modifiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/weightModifier"
                    }
                }
            }
        },
        "weightModifier": {
            "type": "object",
            "required": [
                "Type"
            ],
            "additionalProperties": true,
            "properties": {
                "Type": {
                    "type": "string",
                    "enum": [
                        "ReelWeight",
                        "CountWeight"
                    ]
                },
                "ReelMultipliers": {
                    "type": "array",
                    "items": {
                        "type": "number",
                        "minimum": 0
                    }
                },
                "Scales": {
                    "type": "array",
                    "items": {
                        "type": "number",
                        "minimum": 0
                    }
                }
            },
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "ReelWeight"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "ReelMultipliers"
                        ]
                    }
                },
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "CountWeight"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "Scales"
                        ]
                    }
                }
            ]
        },
        "feature": {
            "type": "object",
            "required": [
                "Type"
            ],
            "additionalProperties": true,
            "properties": {
                "Type": {
                    "type": "string"
                },
                "TargetSymbolID": {
                    "type": "integer"
                },
                "FeatureSymbol": {
                    "$ref": "#/definitions/symbol"
                },
                "Paylines": {
                    "type": "array"
                },
                "ExcludeSymbolIDs": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "Features": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/feature"
                    }
                },
                "FreeSpins": {
                    "type": "integer"
                },
                "ClusterSize": {
                    "type": "integer"
                }
            },
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "EXPANDING_WILDS_FEATURE"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "TargetSymbolID"
                        ]
                    }
                },
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "SCATTER_FEATURE"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "FeatureSymbol"
                        ]
                    }
                },
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "PAYLINES_FEATURE"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "Paylines"
                        ]
                    }
                },
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "FREE_SPINS_FEATURE"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "FreeSpins",
                            "Features",
                            "FeatureSymbol"
                        ]
                    }
                },
                {
                    "if": {
                        "properties": {
                            "Type": {
                                "const": "CLUSTER_FEATURE"
                            }
                        }
                    },
                    "then": {
                        "required": [
                            "ClusterSize"
                        ]
                    }
                }
            ]
        }
    }
}

=== Gurraza/project-slots-backend/internal/games/lines.json
{
    "Cols": 5,
    "Rows": 3,
    "Symbols": [
        {
            "ID": 1,
            "Name": "Cherry",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 2,
            "Name": "Strawberry",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 3,
            "Name": "Citrus",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 4,
            "Name": "Orange",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 5,
            "Name": "Banana",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 6,
            "Name": "Bar1",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        }
    ],
    "Features": [
        {
            "Type": "WILD_FEATURE",
            "FeatureSymbol": {
                "ID": 7,
                "Name": "Wild",
                "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
                "MatchesWith": [ "*" ],
                "WeightConfig": {
                    "FixedWeight": 100,
                    "Modifiers": [
                        { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                    ]
                }
            }
        },
        {
            "Type": "EXPANDING_WILDS_FEATURE",
            "TargetSymbolID": 7
        },
        {
            "Type": "PAYLINES_FEATURE",
            "Paylines": [
                [ 0, 0, 0, 0, 0 ],
                [ 1, 1, 1, 1, 1 ],
                [ 2, 2, 2, 2, 2 ],
                [ 0, 1, 2, 1, 0 ],
                [ 2, 1, 0, 1, 2 ]
            ],
            "ExcludeSymbolIDs": [ 63 ]
        }
    ]
}

=== Gurraza/project-slots-backend/internal/games/clashofreels.json
{
    "Cols": 7,
    "Rows": 7,
    "Symbols": [
        {
            "ID": 0,
            "Name": "Barbarian",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 1,
            "Name": "Archer",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 2,
            "Name": "Goblin",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 3,
            "Name": "Minion",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 4,
            "Name": "Pekka",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 5,
            "Name": "Gem",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 6,
            "Name": "DarkElixir",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 7,
            "Name": "Elixir",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        },
        {
            "ID": 8,
            "Name": "Gold",
            "Payouts": [ 0, 0, 2.5, 5.0, 10.0 ],
            "MatchesWith": [ ],
            "WeightConfig": {
                "FixedWeight": 100,
                "Modifiers": [
                    { "Type": "ReelWeight", "ReelMultipliers": [ 100, 100, 100, 50, 50 ] }
                ]
            }
        }
    ],
    "Features": [
        {
            "Type": "CLUSTER_FEATURE",
            "ClusterSize": 4
        }
    ]
}
